name: Build and Publish

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build_wheels:
    name: Build {{ matrix.submodule }} wheels on ${{ matrix.os }} for CPython ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python: [cp39, cp310, cp311, cp312]
        submodule: [quspin-basis-general-extensions, quspin-basis-1d-extensions]
    steps:
      - uses: actions/checkout@v4
      - name: Get boost headers
        working-directory: ${{ github.workspace }}/${{ matrix.submodule }}
        run: |
          curl -L -O https://github.com/scipy/boost-headers-only/archive/refs/heads/main.zip
          7z x main.zip
          mkdir src/quspin/extensions/includes
          cp -r boost-headers-only-main/boost src/quspin/extensions/includes

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: ${{ github.workspace }}/${{ matrix.submodule }}
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_ENVIRONMENT: BOOST_ROOT=src/quspin/extensions/includes
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.submodule }}-${{ matrix.os }}-${{ matrix.python }}
          path: ${{ github.workspace }}/${{ matrix.submodule }}/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution for ${{ matrix.submodule }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule: [quspin-basis-general-extensions, quspin-basis-1d-extensions]

    steps:
      - uses: actions/checkout@v4
      - name: Get boost headers
        working-directory: ${{matrix.submodule}}
        run: |
          curl -L -O https://github.com/scipy/boost-headers-only/archive/refs/heads/main.zip
          7z x main.zip
          mkdir ${{github.workspace}}/quspin-basis-general-extensions/src/quspin/extensions/includes
          cp -r boost-headers-only-main/boost ${{github.workspace}}/quspin-basis-general-extensions/src/quspin/extensions/includes

      - name: Build sdist
        run: pipx run build --sdist
        working-directory: ${{matrix.submodule}}
        env:
          BOOST_ROOT: ${{github.workspace}}/{{ matrix.submodule }}/src/quspin/extensions/includes

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, build_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true